
stages:
- dependencies
- build

# ==========
# DEPENDENCIES
# ==========
Build dependency-image:
  stage: dependencies
  image: docker:20.10.23-cli
  services:
  - docker:20.10.23-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
    CI_DOCKER_TAG: "${CI_COMMIT_BRANCH}"
  before_script:
  - apk add --no-cache --update bash git
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
  - ./make docker build dependency
  - ./make docker push dependency

# ==========
# BUILD
# ==========
Build runtime-image:
  stage: build
  image: docker:20.10.23-cli
  services:
  - docker:20.10.23-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
    CI_DOCKER_TAG: "${CI_COMMIT_BRANCH}"
  before_script:
  - apk add --no-cache --update bash git
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
  - ./make docker build
  - ./make docker push
