version: '3.8'
services:
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PUBLIC_PORT:-6379}:6379"
    volumes:
      - redis_data:/bitnami

volumes:
  redis_data:
