version: '3.8'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "${POSTGRES_PUBLIC_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=server
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PUBLIC_PORT:-6379}:6379"
    volumes:
      - redis_data:/bitnami

volumes:
  postgres-data:
  redis_data: